name: Keep Supabase Alive

on:
  schedule:
    # Jalan otomatis setiap hari jam 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Ini biar lu bisa klik tombol "Run workflow" manual di GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Supabase REST API
        run: |
          curl -X GET "https://keaqwqdifwhgcyatpimo.supabase.co/rest/v1/Order?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
